[package]
name = "gtfo-codecracker"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
eframe = "0.32.1"
image = "0.25.6"
rdev = "0.5"
winit = "0.30.12"

[build-dependencies]
winres = "0.1"
